language: cpp
dist: xenial
compiler: gcc

script: 
  - gcc MiniPreimere.cpp -o MiniPreimere 

before_deploy:
  - git config --global user.name "$USER_NAME"
  - git config --global user.email "$USER_EMAIL" 
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $GIT_TAG"


deploy:
  provider: releases
  api_key: $GIT_TOKEN 
  file:
    - MiniPreimere 
  name: MiniPremiere-GIT_TAG
  skip-cleanup: true
  on:
    tags: true
    repo: ZhuYuanMing/LearnSpace 
    branches:
      only:
        - master
