language: cpp
dist: xenial
compiler: gcc

script: 
  - gcc MiniPreimere.cpp -o MiniPreimere 

before_deploy:
  - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - git config --global user.name "$USER_NAME"
  - git config --global user.email "$USER_EMAIL" 
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  tag_name = $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  overwirte: true
  api_key: $GIT_TOKEN 
  file:
    - MiniPreimere 
  name: MiniPlayer-$TRAVIS_TAG
  skip-cleanup: true
  on:
    tags: true
    repo: ZhuYuanMing/LearnSpace 
    branches:
      only:
        - master
