language: cpp
dist: xenial
compiler: gcc

script: 
  - gcc MiniPreimere.cpp -o MiniPreimere 

before_deploy:
  - git config --global user.name "ZhuYuanMing"
  - git config --global user.email "317012994@zju.edu.cn"
  - export GIT_TAG=1.0.0
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $GIT_TAG"
  - git push origin $GIT_TAG

deploy:
  provider: releases
  api_key: XX6UaPV0mU2XB6mw02ayvg
  file:
    - MiniPreimere 
  name: MiniPremiere-1.0.0
  skip-cleanup: true
  on:
    tags: true
    repo: ZhuYuanMing/LearnSpace 
    branches:
      only:
        - master

