language: cpp
dist: xenial
compiler: gcc

script: 
  - gcc MiniPreimere.cpp -o MiniPreimere 
before_deploy:
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - export GIT_TAG=1.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - MiniPreimere 
  name: MiniPremiere-1.0.$TRAVIS_BUILD_NUMBER
  skip-cleanup: true
  on:
    tags: true
    repo: ZhuYuanMing/LearnSpace 
    branches:
      only:
        - master

